### PR TITLE
updated mltable version

### PR DESCRIPTION
**Pull request by wutaomsft**

### CODE REVIEW

**Review by wutaomsft — COMMENTED** [review]
mltable version updated

**Review by wutaomsft — COMMENTED** [review]
mltable

**Review by wutaomsft — COMMENTED** [review]
update mltable

**Comment by kicha0** [comment]
this PR updates the mltable version to b4:
https://github.com/Azure/RAI-vNext-Preview/pull/133/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

Closing your PR since its already updated.

**Pull request closed without merging**
